spring.jpa.hibernate.ddl-auto=validate

# Garante que o Flyway rode as migrações no H2 antes de qualquer validacao
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=